//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.31 at 07:49:50 PM GMT+02:00 
//


package connectoin.params;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="engines">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="engine" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="drivertype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "engines"
})
@XmlRootElement(name = "databaseServers")
public class DatabaseServers {

    @XmlElement(required = true)
    protected DatabaseServers.Engines engines;

    /**
     * Gets the value of the engines property.
     * 
     * @return
     *     possible object is
     *     {@link DatabaseServers.Engines }
     *     
     */
    public DatabaseServers.Engines getEngines() {
        return engines;
    }

    /**
     * Sets the value of the engines property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatabaseServers.Engines }
     *     
     */
    public void setEngines(DatabaseServers.Engines value) {
        this.engines = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="engine" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="drivertype" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "engine"
    })
    public static class Engines {

        protected List<DatabaseServers.Engines.Engine> engine;

        /**
         * Gets the value of the engine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the engine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEngine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DatabaseServers.Engines.Engine }
         * 
         * 
         */
        public List<DatabaseServers.Engines.Engine> getEngine() {
            if (engine == null) {
                engine = new ArrayList<DatabaseServers.Engines.Engine>();
            }
            return this.engine;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="user" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="port" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="host" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="schema" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="drivertype" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="protocol" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="priority" type="{http://www.w3.org/2001/XMLSchema}byte" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "user",
            "password",
            "port",
            "host",
            "instance",
            "schema",
            "drivertype",
            "protocol"
        })
        public static class Engine {

            @XmlElement(required = true)
            protected String user;
            @XmlElement(required = true)
            protected String password;
            protected short port;
            @XmlElement(required = true)
            protected String host;
            @XmlElement(required = true)
            protected String instance;
            @XmlElement(required = true)
            protected String schema;
            @XmlElement(required = true)
            protected String drivertype;
            @XmlElement(required = true)
            protected String protocol;
            @XmlAttribute(name = "name")
            protected String name;
            @XmlAttribute(name = "priority")
            protected Byte priority;

            /**
             * Gets the value of the user property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUser() {
                return user;
            }

            /**
             * Sets the value of the user property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUser(String value) {
                this.user = value;
            }

            /**
             * Gets the value of the password property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPassword() {
                return password;
            }

            /**
             * Sets the value of the password property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPassword(String value) {
                this.password = value;
            }

            /**
             * Gets the value of the port property.
             * 
             */
            public short getPort() {
                return port;
            }

            /**
             * Sets the value of the port property.
             * 
             */
            public void setPort(short value) {
                this.port = value;
            }

            /**
             * Gets the value of the host property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHost() {
                return host;
            }

            /**
             * Sets the value of the host property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHost(String value) {
                this.host = value;
            }

            /**
             * Gets the value of the instance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInstance() {
                return instance;
            }

            /**
             * Sets the value of the instance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInstance(String value) {
                this.instance = value;
            }

            /**
             * Gets the value of the schema property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSchema() {
                return schema;
            }

            /**
             * Sets the value of the schema property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSchema(String value) {
                this.schema = value;
            }

            /**
             * Gets the value of the drivertype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDrivertype() {
                return drivertype;
            }

            /**
             * Sets the value of the drivertype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDrivertype(String value) {
                this.drivertype = value;
            }

            /**
             * Gets the value of the protocol property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProtocol() {
                return protocol;
            }

            /**
             * Sets the value of the protocol property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProtocol(String value) {
                this.protocol = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the priority property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getPriority() {
                return priority;
            }

            /**
             * Sets the value of the priority property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setPriority(Byte value) {
                this.priority = value;
            }

        }

    }

}
